"""
Streamlit web app for the PubMed diabetes RAG system.

Run from the project root:
    streamlit run app.py
"""

import streamlit as st

from config import LLM_MODEL, MIN_SIMILARITY, TOP_K
from src.pipeline import STATUS_ERROR, STATUS_NO_RESULTS, answer_question
from src.retriever import index_info
from src.store import IndexNotReadyError

PUBMED_URL = "https://pubmed.ncbi.nlm.nih.gov/{}/"


def md(text):
    """Escape characters Streamlit markdown would misread ($ starts LaTeX maths)."""
    return (text or "").replace("$", "\\$")


@st.cache_resource(show_spinner="Loading the knowledge base...")
def load_knowledge_base():
    """Load the index and embedding model once per server process."""
    return index_info()


# ── Page ─────────────────────────────────────────────────────────────────────
st.set_page_config(page_title="Diabetes Research Assistant", page_icon="🧬", layout="centered")

st.title("🧬 Diabetes Research Assistant")
st.write("Ask questions about diabetes research and get answers grounded in PubMed abstracts, with sources.")
st.info(
    "**Research tool, not medical advice.** Answers are generated by an AI from PubMed abstracts "
    "and may be incomplete or wrong. Always check the sources, and talk to a healthcare "
    "professional about your own health.",
    icon="⚕️",
)

try:
    info = load_knowledge_base()
except IndexNotReadyError as e:
    st.error("The knowledge base isn't ready yet. Build it from the project folder, then refresh this page.")
    st.code(str(e), language=None)
    st.stop()

# ── Sidebar: settings and facts about the knowledge base ─────────────────────
chunks_meta = info.get("chunks_meta", {})
fetch = chunks_meta.get("source_fetch", {})
with st.sidebar:
    st.header("Settings")
    top_k = st.slider("Sources to retrieve", min_value=1, max_value=10, value=TOP_K)

    st.header("Knowledge base")
    if chunks_meta.get("abstracts_used"):
        st.markdown(f"**{chunks_meta['abstracts_used']:,}** PubMed abstracts")
    if fetch.get("from_year") and fetch.get("to_year"):
        st.markdown(f"Published **{fetch['from_year']}–{fetch['to_year']}**")
    st.markdown(f"**{info['n_vectors']:,}** searchable chunks")
    st.caption(
        f"Embeddings: {info['embedding_model']}  \n"
        f"LLM: {LLM_MODEL} (via Ollama)  \n"
        f"Relevance threshold: {MIN_SIMILARITY}  \n"
        f"Index built: {info.get('built_at', '?')[:10]}"
    )
    st.caption(
        "Similarity is the cosine similarity between your question and a source excerpt: "
        "higher means more relevant."
    )

# ── Question form (pressing Enter also submits) ──────────────────────────────
with st.form("ask"):
    query = st.text_input(
        "Your question",
        placeholder="e.g. Do SGLT2 inhibitors reduce heart failure hospitalisation?",
    )
    submitted = st.form_submit_button("🔍 Ask")

if submitted and not query.strip():
    st.warning("Please enter a question first.")
elif submitted:
    with st.spinner("Searching the knowledge base and writing an answer..."):
        result = answer_question(query, top_k=top_k)

    if result.status == STATUS_NO_RESULTS:
        st.warning(
            "No sufficiently relevant papers were found for that question. "
            "Try rephrasing, or ask something more specific to diabetes research."
        )
    elif result.status == STATUS_ERROR:
        st.error(f"Couldn't generate an answer. {result.error}")
    else:
        st.subheader("💬 Answer")
        st.markdown(md(result.answer))

    if result.sources:
        st.subheader("📚 Sources")
        st.caption(f"{len(result.sources)} excerpt(s), most relevant first.")
        for i, s in enumerate(result.sources, 1):
            title = s.get("title") or "Untitled"
            year = f" ({s['year']})" if s.get("year") else ""
            with st.expander(md(f"[{i}] {title}{year}")):
                byline = " · ".join(
                    x for x in (s.get("authors_display"), f"*{s['journal']}*" if s.get("journal") else None) if x
                )
                if byline:
                    st.markdown(md(byline))
                part = ""
                if s.get("n_chunks_in_source", 0) > 1:
                    part = f" · excerpt {s['chunk_index'] + 1} of {s['n_chunks_in_source']}"
                st.caption(f"PMID {s['pmid']} · similarity {s['score']:.2f}{part}")
                st.markdown(md(s["text"]))
                st.markdown(f"[View on PubMed ↗]({PUBMED_URL.format(s['pmid'])})")

st.divider()
st.caption("Built with Streamlit · FAISS · Sentence Transformers · Ollama · PubMed E-utilities")
